version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:8.15.0-browsers
    working_directory: ~/ami-ledger
jobs:
  build:
    executor: node
    steps:
      - checkout
      - restore_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --non-interactive --cache-folder ~/.cache/yarn 
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          Name: No-op
          command: yarn --version
  lint:
    executor: node
    steps:
      - checkout
      - restore_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --non-interactive --cache-folder ~/.cache/yarn 
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          Name: Lint
          command: yarn run lint
  prettier:
    executor: node
    steps:
      - checkout
      - restore_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --non-interactive --cache-folder ~/.cache/yarn 
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Prettier
          command: yarn run prettier
  test:
    executor: node
    steps:
      - checkout
      - restore_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --non-interactive --cache-folder ~/.cache/yarn 
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Jest testing
          command: yarn run test
      - store_test_results:
          path: reports/jest
workflows:
  build-lint-test:
    jobs:
      - build
      - lint
      - prettier
      - test:
          context: aws-dev
  deploy:
    jobs:
      - build
