version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0-browser
    working_directory: ~/ami-ledger
    steps:
      - checkout
      - restore-cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --non-interactive --cache-folder ~/.cache/yarn 
      - save-cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          Name: No-op
          command: yarn --version
  lint:
    docker:
      - image: circleci/node:8.10.0-browser
    working_directory: ~/ami-ledger
    steps:
      - checkout
      - restore-cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --non-interactive --cache-folder ~/.cache/yarn 
      - save-cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          Name: Lint
          command: yarn run lint
  prettier:
    docker:
      - image: circleci/node:8.10.0-browser
    working_directory: ~/ami-ledger
    steps:
      - checkout
      - restore-cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --non-interactive --cache-folder ~/.cache/yarn 
      - save-cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Prettier
          command: yarn run prettier
  test:
    docker:
      - image: circleci/node:8.10.0-browser
    working_directory: ~/ami-ledger
    steps:
      - checkout
      - restore-cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --non-interactive --cache-folder ~/.cache/yarn 
      - save-cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Jest testing
          command: yarn run test
      - store_test_results:
          path: ~/reports/junit
workflows:
  build-lint-test:
    jobs:
      - build
      - lint
      - prettier
      - test
  deploy:
    jobs:
      - build
